// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createMockSupabaseClient() {
  const dummyChain = () => {
    const chain: any = {
      select: () => chain,
      insert: () => Promise.resolve({ data: null, error: null }),
      update: () => chain,
      delete: () => chain,
      eq: () => chain,
      order: () => chain,
      limit: () => chain,
      maybeSingle: () => Promise.resolve({ data: null, error: null }),
      then: (onfulfilled: any) => Promise.resolve({ data: null, error: null }).then(onfulfilled),
      catch: (onrejected: any) => Promise.resolve({ data: null, error: null }).catch(onrejected),
      finally: (onfinally: any) => Promise.resolve({ data: null, error: null }).finally(onfinally),
    };
    return chain;
  };

  const mockClient: any = {
    auth: {
      onAuthStateChange: (callback: any) => {
        setTimeout(() => callback("INITIAL_SESSION", null), 0);
        return { data: { subscription: { unsubscribe: () => {} } } };
      },
      getSession: () => Promise.resolve({ data: { session: null } }),
      signInWithPassword: () => Promise.resolve({ data: { user: null, session: null }, error: null }),
      signUp: () => Promise.resolve({ data: { user: null, session: null }, error: null }),
      signOut: () => Promise.resolve({ error: null }),
    },
    from: () => dummyChain(),
    channel: () => {
      const channel: any = {
        on: () => channel,
        subscribe: () => channel,
      };
      return channel;
    },
    removeChannel: () => Promise.resolve(),
  };

  return mockClient;
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (
    !SUPABASE_URL || 
    !SUPABASE_PUBLISHABLE_KEY || 
    SUPABASE_URL === 'undefined' || 
    SUPABASE_PUBLISHABLE_KEY === 'undefined' ||
    SUPABASE_URL === '' ||
    SUPABASE_PUBLISHABLE_KEY === ''
  ) {
    const missing = [
      ...(!SUPABASE_URL || SUPABASE_URL === 'undefined' || SUPABASE_URL === '' ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY || SUPABASE_PUBLISHABLE_KEY === 'undefined' || SUPABASE_PUBLISHABLE_KEY === '' ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    console.warn(`[Supabase] Missing or undefined Supabase environment variable(s): ${missing.join(', ')}. Using mock client instead.`);
    return createMockSupabaseClient() as ReturnType<typeof createClient<Database>>;
  }

  try {
    return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: typeof window !== 'undefined' ? localStorage : undefined,
        persistSession: true,
        autoRefreshToken: true,
      }
    });
  } catch (err) {
    console.error("[Supabase] Failed to initialize Supabase client. Falling back to mock client.", err);
    return createMockSupabaseClient() as ReturnType<typeof createClient<Database>>;
  }
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});


